table "Tables/Fonts/MainFont.txt"

DATA_848000:
	db "JOHN'S CHEAT",$FF

DATA_84800D:
	db "LYNDON'S CHEAT",$FF

DATA_84801C:
	db "NINTENDO POWER",$FF

DATA_84802B:
	db "BAD INFLUENCE!",$FF

DATA_84803A:
	db "DERNIER SCORE",$FF

DATA_848048:
	db "      PLOK ARRIVE CHEZ        ",$FF

DATA_848067:
	db "   LUI LE LENDEMAIN MATIN...  ",$FF

DATA_848086:
	db "     PLOK JOUA SA VIE EN      ",$FF

DATA_8480A5:
	db "       DESCENDANT DANS        ",$FF

DATA_8480C4:
	db "      LE TROU DE PUCES!       ",$FF

DATA_8480E3:
	db "  EXACTEMENT AU MEME ENDROIT, ",$FF

DATA_848102:
	db "  CINQUANTE ANS PLUS TOT, LE  ",$FF

DATA_848121:
	db " GRAND-PERE DE PLOK CHERCHAIT ",$FF

DATA_848140:
	db " AUSSI L'AMULETTE PERDUE...   ",$FF

DATA_84815F:
	db "  QU'EST-CE?  ",$FF

DATA_84816E:
	db "  L'AMULETTE  ",$FF

DATA_84817D:
	db "  PERDUE PAR  ",$FF

DATA_84818C:
	db " GRAND-PERE!  ",$FF

DATA_84819B:
	db "    PERDU!!   ",$FF

DATA_8481AA:
	db "&&&&",$FF

DATA_8481AF:
	db " RECOMMENCEZ  ",$FF

DATA_8481BE:
	db " PRESSEZ START",$FF

DATA_8481CD:
	db "    NIVEAUX   ",$FF

DATA_8481DC:
	db "    NORMAL    ",$FF

DATA_8481EB:
	db " JEU D'ENFANT ",$FF

DATA_8481FA:
	db "TROU DE PUCES ",$FF

DATA_848209:
	db "TEST DRIVE",$FF

DATA_848214:
	db "  ILE  COTON  ",$FF

DATA_848223:
	db "    ILE     ",$FF

DATA_848230:
	db "  HERITAGE  ",$FF

DATA_84823D:
	db "   AKRILLIC   ",$FF

DATA_84824C:
	db " PLAGE GARLEN ",$FF

DATA_84825B:
	db " VAL  ENDORMI ",$FF

DATA_84826A:
	db "  CHEZ PLOK   ",$FF

DATA_848279:
	db "    PAR UN    ",$FF

DATA_848288:
	db "  BEAU MATIN  ",$FF

DATA_848297:
	db " VILLE DE PLOK",$FF

DATA_8482A6:
	db " LES PENKINOS ",$FF

DATA_8482B5:
	db "  TERMITIERES ",$FF

DATA_8482C4:
	db "CRIQUE DE REVE",$FF

DATA_8482D3:
	db "BOIS  SINISTRE",$FF

DATA_8482E2:
	db "   WOMACK!    ",$FF

DATA_8482F1:
	db "ROC TERRIFIANT",$FF

DATA_848300:
	db "    GROTTE    ",$FF

DATA_84830F:
	db "CHUTE DE ROCS ",$FF

DATA_84831E:
	db "  ROCKYFELLA  ",$FF

DATA_84832D:
	db "BRENDAMMI  BOG",$FF

DATA_84833C:
	db " BADREAM FENS ",$FF

DATA_84834B:
	db " BREEZY BEACH ",$FF

DATA_84835A:
	db "ANSE DE MACE",$FF

DATA_848367:
	db "TROU DU FOU ",$FF

DATA_848374:
	db "  ZIG  ZAG  ",$FF

DATA_848381:
	db "BLOCS POREUX",$FF

DATA_84838E:
	db "BREF  APERCU",$FF

DATA_84839B:
	db "CHEMIN BOISE",$FF

DATA_8483A8:
	db "BUTTE  TAPIE",$FF

DATA_8483B5:
	db " PEDALER RUSE ",$FF

DATA_8483C4:
	db " TOUT TERRAIN ",$FF

DATA_8483D3:
	db "  UNE  FUSEE  ",$FF

DATA_8483E2:
	db "     MOTO     ",$FF

DATA_8483F1:
	db "    HELICO!   ",$FF

DATA_848400:
	db "     TANK     ",$FF

DATA_84840F:
	db "   O.V.N.I.   ",$FF

DATA_84841E:
	db "   LEVEL 1!   ",$FF

DATA_84842D:
	db "   LEVEL 2!   ",$FF

DATA_84843C:
	db "   LEVEL 3!   ",$FF

DATA_84844B:
	db "   LEVEL 4!   ",$FF

DATA_84845A:
	db "   LEVEL 5!   ",$FF

DATA_848469:
	db "   LEVEL 6!   ",$FF

DATA_848478:
	db "   LEVEL 7!   ",$FF

DATA_848487:
	db "   LEVEL 8!   ",$FF

DATA_848496:
	db "   LA PLAGE   ",$FF

DATA_8484A5:
	db "     PONT     ",$FF

DATA_8484B4:
	db "   COLONNES   ",$FF

DATA_8484C3:
	db "CHUTES  RAIDES",$FF

DATA_8484D2:
	db "PONT  BRANLANT",$FF

DATA_8484E1:
	db "PLATES-FORMES ",$FF

DATA_8484F0:
	db "SAUT DE L'ANGE",$FF

DATA_8484FF:
	db "   BOBINE   ",$FF

DATA_84850C:
	db "FRERES  BOBINE",$FF

DATA_84851B:
	db "   LA REINE   ",$FF

DATA_84852A:
	db "  PLOKONTINUE ",$FF

DATA_848539:
	db "  BONUS PLOK  ",$FF

DATA_848548:
	db "    PAUSE     ",$FF

DATA_848557:
	db " INTERRUPTION ",$FF

DATA_848566:
	db "COTTON ISLAND",$FF

DATA_848574:
	db "AKRYLIC 1-8  ",$FF

DATA_848582:
	db "AKRYLIC 9-16 ",$FF

DATA_848590:
	db "PLOK'S LEGACY",$FF

DATA_84859E:
	db "FLEAPIT TEST",$FF

DATA_8485AB:
	db "15.42  5 MAY '93",$FF

DATA_8485BC:
	db " WARP SECRET! ",$FF

DATA_8485CB:
	db " SUPER BONUS! ",$FF

DATA_8485DA:
	db "  ILLEGAL GAME CONFIGURATION  ",$FF

DATA_8485F9:
	db " CE JEU N'EST PAS CONCU POUR  ",$FF

DATA_848618:
	db " VOTRE SUPER FAMICOM NI POUR  ",$FF

DATA_848637:
	db " VOTRE SUPER NES VERSION USA. ",$FF

DATA_848656:
	db "COPYRIGHT TRADEWEST INC. 1993 ",$FF

DATA_848675:
	db "      PLOK&& AND &C& 1993     ",$FF

DATA_848694:
	db "JOHN PICKFORD ET  STE PICKFORD",$FF

DATA_8486B3:
	db "     ALL RIGHTS RESERVED.     ",$FF

DATA_8486D2:
	db "        PLOK IS A U.S.        ",$FF

DATA_8486F1:
	db "     REGISTERED TRADEMARK.    ",$FF

DATA_848710:
	db " LICENSED TO TRADEWEST, INC.  ",$FF

DATA_84872F:
	db "    BY SOFTWARE CREATIONS     ",$FF

DATA_84874E:
	db "       &HOLDINGS& LTD.        ",$FF

DATA_84876D:
	db "    LICENSED TO NINTENDO.     ",$FF

DATA_84878C:
	db "                ",$FF

DATA_84879D:
	db "                                ",$FF

DATA_8487BE:
	db " QUELLE BELLE ",$FF

DATA_8487CD:
	db "  JOURNEE...  ",$FF

DATA_8487DC:
	db " ENSOLEILLEE! ",$FF

DATA_8487EB:
	db "PAS DE SOUCIS.",$FF

DATA_8487FA:
	db "      HO!     &&   IL Y A UN  &&",$FF

DATA_84881B:
	db "  PROBLEME.  ",$FF

DATA_848829:
	db "  OU EST MON  &&GRAND DRAPEAU &&",$FF

DATA_84884A:
	db "   CARRE?    ",$FF

DATA_848858:
	db "  QUELQU'UN   &&ME L'A FAUCHE!",$FF

DATA_848877:
	db "  OU EST-IL   &&   PASSE?     ",$FF

DATA_848896:
	db "  QUI A PRIS  && MON DRAPEAU? ",$FF

DATA_8488B5:
	db "  QUI QUE TU  && SOIS, TU VAS &&",$FF

DATA_8488D6:
	db "LE REGRETTER.",$FF

DATA_8488E4:
	db "         OU EST-IL?!!!!       ",$FF

DATA_848903:
	db "HEU, SUR LE ROCHER TERRIFIANT?",$FF

DATA_848922:
	db "             NON!             ",$FF

DATA_848941:
	db "  DANS LE MARECAGE BRENDAMI?  ",$FF

DATA_848960:
	db "     SUR LA PLAGE VENTEE?     ",$FF

DATA_84897F:
	db "  MAIS OU PEUT-IL BIEN ETRE?  ",$FF

DATA_84899E:
	db "        AH, IL EST LA,        ",$FF

DATA_8489BD:
	db "      SUR L'ILE COTON!        ",$FF

DATA_8489DC:
	db "        CA VA BARDER!         & ",$FF

DATA_8489FD:
	db "    JE VAIS LE PRENDRE      &  E",$FF

DATA_848A1E:
	db " MES MEMBRES VONT FUSER!  ",$FF

DATA_848A39:
	db " C'EST MIEUX! ",$FF

DATA_848A48:
	db " SI SEULEMENT ",$FF

DATA_848A57:
	db "  GRAND-PERE  ",$FF

DATA_848A66:
	db "AVAIT RETROUVE",$FF

DATA_848A75:
	db "  L'AMULETTE, ",$FF

DATA_848A84:
	db " CA M'AURAIT  ",$FF

DATA_848A93:
	db " AIDE A VENIR ",$FF

DATA_848AA2:
	db "A BOUT DE CES ",$FF

DATA_848AB1:
	db "PUCES INFAMES!",$FF

DATA_848AC0:
	db "    ZZZZZZ    ",$FF

DATA_848ACF:
	db "COURSE  CONTRE",$FF

DATA_848ADE:
	db "  LA  MONTRE  ",$FF

DATA_848AED:
	db "A VOS MARQUES!",$FF

DATA_848AFC:
	db "     PRET!    ",$FF

DATA_848B0B:
	db "    PARTEZ!   ",$FF

DATA_848B1A:
	db "COURSE PERDUE!",$FF

DATA_848B29:
	db "J.L.D.P.BUCKLEY! POUR DEPLACER P",$FF

DATA_848B4A:
	db "OK, APPUYEZ  ",$FF

DATA_848B58:
	db " VERS LA DROITE OU LA GAUCHE. ",$FF

DATA_848B77:
	db "     APPUYEZ VERS LE BAS      ",$FF

DATA_848B96:
	db "  POUR QU'IL S'ACCROUPISSE.   ",$FF

DATA_848BB5:
	db " VOUS GLISSEREZ SUR DES PENTES",$FF

DATA_848BD4:
	db "DEFENDEZ PLOK EN APPUYANT SUR ",$FF

DATA_848BF3:
	db " 'Y' POUR LANCER SES MEMBRES. ",$FF

DATA_848C12:
	db "APPUYEZ  SUR 'B' POUR SAUTER. ",$FF

DATA_848C31:
	db "   APPUYEZ SUR LE BOUTON 'A'  ",$FF

DATA_848C50:
	db "POUR FAIRE DES SAUTS PERILLEUX",$FF

DATA_848C6F:
	db "    EVITEZ DES OBSTACLES!     ",$FF

DATA_848C8E:
	db "   RAMASSEZ LES COQUILLAGES   ",$FF

DATA_848CAD:
	db "     POUR LE BONUS PLOK.      ",$FF

DATA_848CCC:
	db "SAUTEZ AU-DESSUS DES DRAPEAUX ",$FF

DATA_848CEB:
	db "  POUR TERMINER LE NIVEAU!    ",$FF

DATA_848D0A:
	db "    PERDRE LES DEUX JAMBES    ",$FF

DATA_848D29:
	db "    REND LA VIE DIFFICILE!    ",$FF

DATA_848D48:
	db "     UNE BONNE SURPRISE?      ",$FF

DATA_848D67:
	db "       UN COSTUME P-UP!       ",$FF

DATA_848D86:
	db "  DES COSTUMES P-UP PEUVENT   ",$FF

DATA_848DA5:
	db "  ATTEINDRE PLUS D'ENNEMIS!   ",$FF

DATA_848DC4:
	db "  PRENEZ GARDE!...ROCKYFELLA  ",$FF

DATA_848DE3:
	db "  PEUT SE CACHER LA-DESSOUS   ",$FF

DATA_848E02:
	db "  PRENEZ LA PIERRE PRECIEUSE  ",$FF

DATA_848E21:
	db "      CA VOUS PROTEGERA       ",$FF

DATA_848E40:
	db "       TEMPORAIREMENT!        ",$FF

DATA_848E5F:
	db "   PRENEZ LES FRUITS BONUS    ",$FF

DATA_848E7E:
	db " POUR UN SUPPLEMENT D'ENERGIE!",$FF

DATA_848E9D:
	db " 2 TIRS FONT GONFLER LE FRUIT ",$FF

DATA_848EBC:
	db "    PLUS LE FRUIT EST GROS,   ",$FF

DATA_848EDB:
	db "  PLUS GRANDE EST L'ENERGIE!  ",$FF

DATA_848EFA:
	db "   TIRER UNE TROISIEME FOIS   ",$FF

DATA_848F19:
	db "    FERA ECLATER LE FRUIT!    ",$FF

DATA_848F38:
	db " OU VOUS REVELERA UN SECRET!  ",$FF

DATA_848F57:
	db "    OK NON! PAS CELUI-LA      ",$FF

DATA_848F76:
	db "RAMASSEZ LES ICONES DE VITESSE",$FF

DATA_848F95:
	db "  POUR FOUDROYER LE NIVEAU!   ",$FF

DATA_848FB4:
	db "ELIMINEZ LES ENNEMIS EN ROUTE!",$FF

DATA_848FD3:
	db "      LES FRERES BOBINE       ",$FF

DATA_848FF2:
	db "   LE CIRQUE PSYCHOS ECHOUE   ",$FF

DATA_849011:
	db "UTILISEZ UN MEMBRE POUR VISER.",$FF

DATA_849030:
	db "   POUR FAIRE BOUGER LE SOL   ",$FF

DATA_84904F:
	db " ENLEVEZ LE MEMBRE DU CINTRE  ",$FF

DATA_84906E:
	db "  DES CIBLES A TIRS REPETES!  ",$FF

DATA_84908D:
	db "RAMASSEZ LES NIDS DE FRELONS. ",$FF

DATA_8490AC:
	db "   FAITES ECLORE LES OEUFS    ",$FF

DATA_8490CB:
	db " APPUYEZ SUR LE BOUTON X POUR ",$FF

DATA_8490EA:
	db "   LIBERER LE FRELON AMICAL   ",$FF

DATA_849109:
	db "     TIREZ SUR CES PUCES!     ",$FF

DATA_849128:
	db "    AVEC L'AMULETTE PERDUE,   ",$FF

DATA_849147:
	db "     VOUS POUVEZ........      ",$FF

DATA_849166:
	db " EN UTILISANT DES COQUILLAGES ",$FF

DATA_849185:
	db "   RENDRE PLOK FOU FURIEUX!   ",$FF

DATA_8491A4:
	db "  ANEANTISSEZ CES MECHANTS!   ",$FF

DATA_8491C3:
	db "         LES PENKINOS         ",$FF

DATA_8491E2:
	db "       LES INCROYABLES        ",$FF

DATA_849201:
	db "     MAGICIENS BAUDRUCHES     ",$FF

DATA_849220:
	db "      FRAPPEZ-LES AVEC        ",$FF

DATA_84923F:
	db "      LA 'LANCE TAMBOUR'      ",$FF

DATA_84925E:
	db "TIREZ QUAND ILS SE DEGONFLENT!",$FF

DATA_84927D:
	db " CE N'EST PAS ",$FF

DATA_84928C:
	db " MON DRAPEAU! ",$FF

DATA_84929B:
	db "QU'EST-CE QUI ",$FF

DATA_8492AA:
	db "  SE PASSE?   ",$FF

DATA_8492B9:
	db "  JE ME SUIS  ",$FF

DATA_8492C8:
	db " FAIT AVOIR!  ",$FF

DATA_8492D7:
	db "GRR!! TOUT CA ",$FF

DATA_8492E6:
	db " ME REND FOU! ",$FF

DATA_8492F5:
	db "     HE!!     ",$FF

DATA_849304:
	db "    JE LES    ",$FF

DATA_849313:
	db "  RECONNAIS!  ",$FF

DATA_849322:
	db "  OH!   OHH!! ",$FF

DATA_849331:
	db "   OHHH!!!    ",$FF

DATA_849340:
	db "CE N'EST PLUS ",$FF

DATA_84934F:
	db " TRES  DROLE! ",$FF

DATA_84935E:
	db "   AH!  AH!   ",$FF

DATA_84936D:
	db "   C'ETAIT    ",$FF

DATA_84937C:
	db "  DU GATEAU!  ",$FF

DATA_84938B:
	db "  GRAND-PERE  ",$FF

DATA_84939A:
	db " SERAIT FIER  ",$FF

DATA_8493A9:
	db "    DE MOI    ",$FF

DATA_8493B8:
	db " OUF! JE LEUR ",$FF

DATA_8493C7:
	db " AI MONTRE, A ",$FF

DATA_8493D6:
	db "CEC PUCES QUI ",$FF

DATA_8493E5:
	db "ETAIT LE CHEF!",$FF

DATA_8493F4:
	db "    QUELLE    ",$FF

DATA_849403:
	db "     BELLE    ",$FF

DATA_849412:
	db "      VUE     ",$FF

DATA_849421:
	db "  HURUMPH !!! ",$FF

DATA_849430:
	db " BAH!   ARGH! ",$FF

DATA_84943F:
	db "C'ETAIT LOURD.",$FF

DATA_84944E:
	db "  IL MANQUE   ",$FF

DATA_84945D:
	db "    CELLE     ",$FF

DATA_84946C:
	db "  DE GAUCHE.  ",$FF

DATA_84947B:
	db "SAPERLIPOPETTE",$FF

DATA_84948A:
	db " QUEL TOUPET! ",$FF

DATA_849499:
	db "  VOTRE BUT?  ",$FF

DATA_8494A8:
	db " MON AMULETTE ",$FF

DATA_8494B7:
	db "PERDUE!  CETTE",$FF

DATA_8494C6:
	db "FOIS, JE VAIS ",$FF

DATA_8494D5:
	db "  LA METTRE   ",$FF

DATA_8494E4:
	db " DANS UN LIEU ",$FF

DATA_8494F3:
	db "VRAIMENT SUR. ",$FF

DATA_849502:
	db " BOF! C'ETAIT ",$FF

DATA_849511:
	db " TROP FACILE! ",$FF

DATA_849520:
	db "  ILS SAVENT  ",$FF

DATA_84952F:
	db " QUI EST ROI  ",$FF

DATA_84953E:
	db "DE CETTE ILE! ",$FF

DATA_84954D:
	db "  ENCORE UN   ",$FF

DATA_84955C:
	db "CHER  DRAPEAU ",$FF

DATA_84956B:
	db "     ET NE    ",$FF

DATA_84957A:
	db " REVENEZ PAS! ",$FF

DATA_849589:
	db "UN'AUTRE PUCE ",$FF

DATA_849598:
	db " GIT A TERRE! ",$FF

DATA_8495A7:
	db "  PLUS AUCUN  ",$FF

DATA_8495B6:
	db "PROBLEME AVEC ",$FF

DATA_8495C5:
	db " ELLE. C'EST  ",$FF

DATA_8495D4:
	db "UNE CERTITUDE!",$FF

DATA_8495E3:
	db "AH AH! JE LEUR",$FF

DATA_8495F2:
	db "  AI MONTRE!  ",$FF

DATA_849601:
	db "  OUF! RIEN   ",$FF

DATA_849610:
	db "  DE CASSE... ",$FF

DATA_84961F:
	db "   DERNIER    ",$FF

DATA_84962E:
	db "   DRAPEAU    ",$FF

DATA_84963D:
	db "   DE PUCE!   ",$FF

DATA_84964C:
	db " J'IGNORE LA  ",$FF

DATA_84965B:
	db " RAISON DE CE ",$FF

DATA_84966A:
	db " TINTAMARRE!  ",$FF

DATA_849679:
	db "  ENFIN, DE   ",$FF

DATA_849688:
	db " NOUVEAU SUR  ",$FF

DATA_849697:
	db " DEUX PATTES! ",$FF

DATA_8496A6:
	db " OU SE CACHE  ",$FF

DATA_8496B5:
	db " CETTE REINE  ",$FF

DATA_8496C4:
	db "  DES PUCES?  ",$FF

DATA_8496D3:
	db "    SUPER!    ",$FF

DATA_8496E2:
	db "  J'AIMERAIS  ",$FF

DATA_8496F1:
	db " RECOMMENCER. ",$FF

DATA_849700:
	db "  CE LIEU NE  ",$FF

DATA_84970F:
	db "M'INSPIRE PAS.",$FF

DATA_84971E:
	db "   OUAIS!     ",$FF

DATA_84972D:
	db " J'AI REUSSI  ",$FF

DATA_84973C:
	db " UN BEAU COUP!",$FF

DATA_84974B:
	db "PRENEZ CA DANS",$FF

DATA_84975A:
	db "  LES DENTS!  ",$FF

DATA_849769:
	db " Y ARRIVERAI- ",$FF

DATA_849778:
	db " JE UN JOUR?  ",$FF

DATA_849787:
	db "  YAHH OUH!   ",$FF

DATA_849796:
	db "    OUAHH!    ",$FF

DATA_8497A5:
	db "HA! HA! HAAA! ",$FF

DATA_8497B4:
	db "    J'AI DU FAIRE ERREUR      ",$FF

DATA_8497D3:
	db "      IL EST LA-BAS...        ",$FF

DATA_8497F2:
	db " JE VAIS L'AVOIR CE DRAPEAU!  ",$FF

DATA_849811:
	db " MAIS! CE DRAPEAU EST ANIME!  ",$FF

DATA_849830:
	db "                              ",$FF

DATA_84984F:
	db " VOUS SAVEZ, JE SENS QU'IL SE ",$FF

DATA_84986E:
	db "PASSE QUELQUE CHOSE DE LOUCHE.",$FF

DATA_84988D:
	db "     SI QUELQU'UN SE MOQUE    ",$FF

DATA_8498AC:
	db "     DE PLOK, ALORS IL VA     ",$FF

DATA_8498CB:
	db "       LE PAYER CHER...       ",$FF

DATA_8498EA:
	db "CELUI-LA A INTERET A ETRE MON ",$FF

DATA_849909:
	db "DRAPEAU, SINON JE...JE NE SAIS",$FF

DATA_849928:
	db " PAS CE QUE JE VAIS FAIRE...  ",$FF

DATA_849947:
	db "    HOU HOU! PAR ICI PLOK!    ",$FF

DATA_849966:
	db "       VIENS LE PRENDRE.      ",$FF

DATA_849985:
	db "    AH! C'EST DONC VOUS LES   ",$FF

DATA_8499A4:
	db "  FRERES BOBINE , QUI M'AVEZ  ",$FF

DATA_8499C3:
	db "     FAIT CE MAUVAIS COUP!    ",$FF

DATA_8499E2:
	db " MON GRAND-PERE M'AVAIT BIEN  ",$FF

DATA_849A01:
	db "   PREVENU A VOTRE SUJET...   ",$FF

DATA_849A20:
	db " TU NE RECUPERERAS JAMAIS TON ",$FF

DATA_849A3F:
	db "     DRAPEAU, PLOK! NOUS      ",$FF

DATA_849A5E:
	db "  T'ECRASERONS POUR DE BON!   ",$FF

DATA_849A7D:
	db " CE FUT UNE BONNE JOURNEE...  ",$FF

DATA_849A9C:
	db "MAINTENANT PLUS PERSONNE NE VA",$FF

DATA_849ABB:
	db " M'EMBETER AVEC MES DRAPEAUX. ",$FF

DATA_849ADA:
	db "    J'AI ETE DUPE! DURANT     ",$FF

DATA_849AF9:
	db "  MON SEJOUR SUR L'ILE COTON, ",$FF

DATA_849B18:
	db "  TOUS MES DRAPEAUX ONT ETE   ",$FF

DATA_849B37:
	db "REMPLACES PAR CEUX DES PUCES! ",$FF

DATA_849B56:
	db "  ILS M'ONT VOLE MON DRAPEAU  ",$FF

DATA_849B75:
	db "CARRE POUR M'ELOIGNER, PENDANT",$FF

DATA_849B94:
	db "     QUE LES PUCES NOUS       ",$FF

DATA_849BB3:
	db "ENVAHISSAIENT!  GRR... JE SENS",$FF

DATA_849BD2:
	db "QUE JE VAIS FAIRE UN MASSACRE!",$FF

DATA_849BF1:
	db "   CA VA ETRE DUR. MAIS JE    ",$FF

DATA_849C10:
	db " RECUPERERAI MON ILE MEME SI  ",$FF

DATA_849C2F:
	db " J'Y PASSE TOUTE LA JOURNEE!  ",$FF

DATA_849C4E:
	db "    ENFIN! BIENTOT ARRIVE!    ",$FF

DATA_849C6D:
	db " PAS UNE SALE PUCE N'A INTERET",$FF

DATA_849C8C:
	db "    A SE MONTRER CHEZ MOI!    ",$FF

DATA_849CAB:
	db " UNE CROIX SIGNALE L'ENDROIT. ",$FF

DATA_849CCA:
	db "      J'AI DU L'ENTERRER      ",$FF

DATA_849CE9:
	db "          PAR LA...           ",$FF

DATA_849D08:
	db "    CETTE FOIS, JE SUIS SUR   ",$FF

DATA_849D27:
	db "     QUE C'EST LE BON...      ",$FF

DATA_849D46:
	db "  HUM...MA MEMOIRE N'EST PLUS ",$FF

DATA_849D65:
	db "     CE QU'ELLE ETAIT...      ",$FF

DATA_849D84:
	db " JE DOIS TROUVER L'AMULETTE.  ",$FF

DATA_849DA3:
	db " C'EST UN HERITAGE DE FAMILLE.",$FF

DATA_849DC2:
	db "JE N'AI PLUS L'AGE DE BONDIR! ",$FF

DATA_849DE1:
	db "   COMBIEN EN AI-JE CACHE?    ",$FF

DATA_849E00:
	db "   VOICI MES PIRES ENNEMIS    ",$FF

DATA_849E1F:
	db "    LES FRERES BOBINE! JE     ",$FF

DATA_849E3E:
	db "  PARIE QU'ILS SONT LA CAUSE  ",$FF

DATA_849E5D:
	db "   DE TOUTES CES IDIOTIES.    ",$FF

DATA_849E7C:
	db "  TU CHERCHES QUELQUE CHOSE,  ",$FF

DATA_849E9B:
	db "  PEPE? TU AS PERDU QUELQUE   ",$FF

DATA_849EBA:
	db "   CHOSE? OUAIS, PEUT-ETRE    ",$FF

DATA_849ED9:
	db "       UNE AMULETTE?          ",$FF

DATA_849EF8:
	db "      TAIS-TOI IRVING!        ",$FF

DATA_849F17:
	db "    CHIC! AVEC L'AMULETTE     ",$FF

DATA_849F36:
	db "   MAGIQUE, LES COQUILLAGES   ",$FF

DATA_849F55:
	db "  DONNENT DU POUVOIR A PLOK.  ",$FF

DATA_849F74:
	db "   GARE A VOUS, LES PUCES!    ",$FF

DATA_849F93:
	db " PENDANT QUE J'Y SUIS, IL EST ",$FF

DATA_849FB2:
	db " GRAND TEMPS QUE JE REGLE LEUR",$FF

DATA_849FD1:
	db "   COMPTE A CES PENKINOS...   ",$FF

DATA_849FF0:
	db " CETTE ESPECE D'HORRIBLE PUCE ",$FF

DATA_84A00F:
	db "    VISQUEUSE EST PARTOUT!    ",$FF

DATA_84A02E:
	db "  AKRILLIC SERA DE NOUVEAU A  ",$FF

DATA_84A04D:
	db "        MOI, CA OUI...        ",$FF

DATA_84A06C:
	db "        OUH! ON DIRAIT        ",$FF

DATA_84A08B:
	db "       QUE C'EST HANTE.       ",$FF

DATA_84A0AA:
	db " HUM... JE CROIS QUE JE VAIS  ",$FF

DATA_84A0C9:
	db "RENDRE VISITE A CETTE FAUTEUSE",$FF

DATA_84A0E8:
	db "DE TROUBLES,L'ARAIGNEE WOMACK.",$FF

DATA_84A107:
	db "BON, REMETTONS-NOUS AU TRAVAIL",$FF

DATA_84A126:
	db "   AVEC CES PUCES GLUANTES.   ",$FF

DATA_84A145:
	db "J'AI ETE ENCORE PLOKTASTIQUE! ",$FF

DATA_84A164:
	db " JE ME DEMANDE D'OU VIENNENT  ",$FF

DATA_84A183:
	db "      TOUTES CES PUCES?       ",$FF

DATA_84A1A2:
	db "AKRILLIC SERA ENCORE UNE FOIS ",$FF

DATA_84A1C1:
	db "A MOI SI SEULEMENT J'ARRIVE A ",$FF

DATA_84A1E0:
	db "RENDRE LA RAISON A ROCKYFELLA.",$FF

DATA_84A1FF:
	db "MAINTENANT, ALLONS A LA SOURCE",$FF

DATA_84A21E:
	db "     DE TOUS CES ENNUIS...    ",$FF

DATA_84A23D:
	db "       LE TROU DE PUCES!      ",$FF

DATA_84A25C:
	db "OUHH... CET ENDROIT EST       ",$FF

DATA_84A27B:
	db "ANGOISSANT... OHE REGARDE!    ",$FF

DATA_84A29A:
	db "QUELQU'UN M'A LAISSE UN CADEAU",$FF

DATA_84A2B9:
	db "  HUM... JE CROIS QUE JE NE   ",$FF

DATA_84A2D8:
	db "   SUIS PLUS SUR AKRILLIC...  ",$FF

DATA_84A2F7:
	db "   IL Y A TOUTES SORTES DE    ",$FF

DATA_84A316:
	db "     DROLES DE PUCES ICI!     ",$FF

DATA_84A335:
	db "  HE, ENCORE DES SURPRISES!   ",$FF

DATA_84A354:
	db "       C'EST AMUSANT.         ",$FF

DATA_84A373:
	db "   CES GROTTES DEVIENNENT     ",$FF

DATA_84A392:
	db "     DE PIRE EN PIRE...       ",$FF

DATA_84A3B1:
	db "J'EN CONNAIS UN QUI VA PAYER  ",$FF

DATA_84A3D0:
	db "     CHER CETTE PAGAILLE!     ",$FF

DATA_84A3EF:
	db "CE MAGMA BLEU EST EN TRAIN DE ",$FF

DATA_84A40E:
	db " SOUILLER MES BOTTES ROUGES.  ",$FF

DATA_84A42D:
	db "LA REINE DES PUCES NE SE DOUTE",$FF

DATA_84A44C:
	db "   PAS DE CE QUI L'ATTEND!    ",$FF

DATA_84A46B:
	db "  VENEZ VOIR! JE SUIS VENU A  ",$FF

DATA_84A48A:
	db " BOUT DES PUCES. OUI OU NON?  ",$FF

DATA_84A4A9:
	db "     IDEE ET CONCEPTION       ",$FF

DATA_84A4C8:
	db "  UN JEU SOFTWARE CREATIONS   ",$FF

DATA_84A4E7:
	db "   GRAPHIQUES ET CONCEPTION   ",$FF

DATA_84A506:
	db "        LYNDON BROOKE         ",$FF

DATA_84A525:
	db "   PROGRAMME ET CONCEPTION    ",$FF

DATA_84A544:
	db "         JOHN BUCKLEY         ",$FF

DATA_84A563:
	db "  MUSIQUE ET EFFETS SPECIAUX  ",$FF

DATA_84A582:
	db "  GEOFF FOLLIN ET TIM FOLLIN  ",$FF

DATA_84A5A1:
	db "  GRAPHIQUES SUPPLEMENTAIRES  ",$FF

DATA_84A5C0:
	db "STE PICKFORD ET  DAN WHITWORTH",$FF

DATA_84A5DF:
	db "      CREATION ARTISTIQUE     ",$FF

DATA_84A5FE:
	db "  STE PICKFORD ET CHRIS JOJO  ",$FF

DATA_84A61D:
	db "  TECHNIQUES DE COMPRESSION   ",$FF

DATA_84A63C:
	db "  STE RUDDY ET KEVIN EDWARDS  ",$FF

DATA_84A65B:
	db "           TESTEURS           ",$FF

DATA_84A67A:
	db "       MALCOLM DAGLISH        ",$FF

DATA_84A699:
	db "        CHUN WAH KONG         ",$FF

DATA_84A6B8:
	db "       REMERCIEMENTS A        ",$FF

DATA_84A6D7:
	db " MIKE WEBB      BRIAN ULLRICH ",$FF

DATA_84A6F6:
	db "  DAVE MAC      STEVE THOMAS  ",$FF

DATA_84A715:
	db "     VERONIQUE CHANTEL        ",$FF

DATA_84A734:
	db "        LIANE ASHLEY          ",$FF

DATA_84A753:
	db "         TONY HARMAN          ",$FF

DATA_84A772:
	db "           RARE LTD.          ",$FF

DATA_84A791:
	db "        JOEL HOCHBERG         ",$FF

DATA_84A7B0:
	db "       ZIPPO GAMES LTD.       ",$FF

DATA_84A7CF:
	db "          PRODUCTEURS         ",$FF

DATA_84A7EE:
	db "    PRODUCTEURS  EXECUTIFS    ",$FF

DATA_84A80D:
	db "          BYRON COOK          ",$FF

DATA_84A82C:
	db "         RICHARD KAY          ",$FF

DATA_84A84B:
	db "         JOEY TERRITO         ",$FF

DATA_84A86A:
	db "    BRAVO!    ",$FF

DATA_84A879:
	db "  BRAVO! LE BUT EST ATTEINT!  ",$FF

DATA_84A898:
	db "  PLOK A RECONQUIS  AKRILLIC  ",$FF

DATA_84A8B7:
	db "REESSAYEZ LE NIVEAU NORMAL ET ",$FF

DATA_84A8D6:
	db " AIDEZ GRAND-PERE A CHERCHER  ",$FF

DATA_84A8F5:
	db " L'AMULETTE, TROUVER LE TROU  ",$FF

DATA_84A914:
	db "DE PUCES ET DETRUIRE LA REINE.",$FF

cleartable