
DATA_81A6F8:									; Note: Intro cutscene text script
	%PLOK_WriteText($02, $04, !Text_Layer_3, !Text_Palette_1, !Text_Size_Large, !Text_Speed_Fast, $0001, IntroCutscenePart1_Line1)
	%PLOK_WriteText($04, $06, !Text_Layer_3, !Text_Palette_1, !Text_Size_Large, !Text_Speed_Fast, $0001, IntroCutscenePart1_Line2)
	%PLOK_WriteText($05, $08, !Text_Layer_3, !Text_Palette_1, !Text_Size_Large, !Text_Speed_Fast, $0001, IntroCutscenePart1_Line3)
	%PLOK_WriteText($00, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Fast, $008C, ClearLargeLetterLine)
	%PLOK_WriteText($03, $05, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $0001, IntroCutscenePart1_Line4)
	%PLOK_WriteText($04, $07, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $0001, IntroCutscenePart1_Line5)
	%PLOK_WriteText($00, $05, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Fast, $0050, ClearLargeLetterLine)
	%PLOK_WriteText($01, $05, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $0001, IntroCutscenePart1_Line6)
	%PLOK_WriteText($00, $05, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Fast, $0078, ClearLargeLetterLine)
	%PLOK_WriteText($01, $05, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $0001, IntroCutscenePart1_Line7)
	%PLOK_WriteText($00, $05, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Fast, $0050, ClearLargeLetterLine)
	%PLOK_WriteText($03, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $00C8, IntroCutscenePart1_Line8)
	%PLOK_WriteText($00, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Fast, $0050, ClearLargeLetterLine)
	%PLOK_WriteText($03, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $0028, IntroCutscenePart1_Line9)
	%PLOK_WriteText($00, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Fast, $0050, ClearLargeLetterLine)
	%PLOK_WriteText($00, $03, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Fast, $0050, ClearLargeLetterLine)
	%PLOK_WriteText($00, $05, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Fast, $0001, ClearLargeLetterLine)
	%PLOK_WriteText($00, $07, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Fast, $0001, ClearLargeLetterLine)
	%PLOK_WriteText($00, $09, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Fast, $0001, ClearLargeLetterLine)
	dw $FFFF

DATA_81A852:
	%PLOK_WriteText($06, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Slow, $0001, IntroCutscenePart2_Line1)
	%PLOK_WriteText($00, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Fast, $003C, ClearSmallLetterLine)
	%PLOK_WriteText($06, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Slow, $0032, IntroCutscenePart2_Line2)
	%PLOK_WriteText($0D, $06, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Slow, $0050, IntroCutscenePart2_Line3)
	%PLOK_WriteText($00, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Fast, $00B4, ClearSmallLetterLine)
	%PLOK_WriteText($00, $06, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Fast, $0001, ClearSmallLetterLine)
	%PLOK_WriteText($08, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Slow, $008C, IntroCutscenePart2_Line4)
	%PLOK_WriteText($0C, $06, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Slow, $0028, IntroCutscenePart2_Line5)
	%PLOK_WriteText($00, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Fast, $0014, ClearSmallLetterLine)
	%PLOK_WriteText($00, $06, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Fast, $0001, ClearSmallLetterLine)
	%PLOK_WriteText($09, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Slow, $0001, IntroCutscenePart2_Line6)
	%PLOK_WriteText($0D, $06, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Slow, $0014, IntroCutscenePart2_Line7)
	%PLOK_WriteText($00, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Fast, $000A, ClearSmallLetterLine)
	%PLOK_WriteText($00, $06, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Fast, $0001, ClearSmallLetterLine)
	%PLOK_WriteText($02, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Slow, $0001, IntroCutscenePart2_Line8)
	%PLOK_WriteText($00, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Fast, $008C, ClearSmallLetterLine)
	%PLOK_WriteText($00, $06, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Fast, $0001, ClearSmallLetterLine)
	%PLOK_WriteText($02, $07, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Slow, $0050, IntroCutscenePart2_Line9)
	%PLOK_WriteText($04, $09, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Slow, $0001, IntroCutscenePart2_Line10)
	%PLOK_WriteText($00, $07, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Fast, $00B4, ClearSmallLetterLine)
	%PLOK_WriteText($00, $09, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Fast, $0001, ClearSmallLetterLine)
	%PLOK_WriteText($04, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Small, !Text_Speed_Slow, $0050, IntroCutscenePart2_Line11)
	dw $FFFF

DATA_81A904:
	%PLOK_WriteText($01, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $01B8, PloksHouseLevelEnd_Line1)
	%PLOK_WriteText($01, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $00C8, PloksHouseLevelEnd_Line2)
	%PLOK_WriteText($01, $06, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $0001, PloksHouseLevelEnd_Line3)
	%PLOK_WriteText($01, $08, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $0001, PloksHouseLevelEnd_Line4)
	%PLOK_WriteText($01, $0A, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $0001, PloksHouseLevelEnd_Line5)
	%PLOK_WriteText($03, $04, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $008F, PloksHouseLevelEnd_Line6)
	%PLOK_WriteText($02, $06, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $0001, PloksHouseLevelEnd_Line7)
	%PLOK_WriteText($03, $08, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $0001, PloksHouseLevelEnd_Line8)
	%PLOK_WriteText($02, $0A, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $0001, PloksHouseLevelEnd_Line9)
	%PLOK_WriteText($04, $08, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Slow, $0085, PloksHouseLevelEnd_Line10)
	%PLOK_WriteText($00, $08, !Text_Layer_3, !Text_Palette_0, !Text_Size_Large, !Text_Speed_Fast, $0032, ClearLargeLetterLine)
	dw $FFFF
